#!/usr/bin/env bash
# Capture the authoritative DNS zone for a domain into a reviewable baseline.
# Read-only: queries the authoritative nameserver, changes nothing.
#
# Usage: ./capture-dns-baseline.sh [domain] [nameserver]
set -uo pipefail

DOMAIN="${1:-aliwallick.com}"
NS="${2:-$(dig +short NS "$DOMAIN" | head -1)}"

# Hostnames worth probing. AXFR is refused by DreamHost, so an exact zone dump
# is impossible -- this list is the practical substitute. Anything not named
# here would be invisible to us, which is why step 2 keeps DreamHost's NS
# records recoverable until delivery is re-verified.
HOSTS=(www mail webmail smtp imap pop ftp blog cpanel autodiscover autoconfig
       m dev test staging shop store api cdn ns1 ns2 email mailer list lists)
TXT_HOSTS=(_dmarc _domainkey dreamhost._domainkey default._domainkey
           google._domainkey mailchannels._domainkey selector1._domainkey
           selector2._domainkey k1._domainkey _acme-challenge)

echo "; DNS baseline for $DOMAIN"
echo "; captured $(date -u '+%Y-%m-%dT%H:%M:%SZ') from authoritative NS: $NS"
echo "; generated by infra/capture-dns-baseline.sh -- do not hand-edit"
echo ";"
echo "; NOTE: TXT records are printed as dig returns them. Multi-string TXT"
echo ";       values (see DKIM) are shown BOTH split and concatenated; the"
echo ";       concatenated form is what you paste into a DNS dashboard."
echo

echo ";; --- apex ---"
for t in SOA NS A AAAA MX TXT CAA SRV; do
  dig +noall +answer @"$NS" "$DOMAIN" "$t"
done

echo
echo ";; --- subdomains (probed; see HOSTS list in script) ---"
for h in "${HOSTS[@]}"; do
  # A CNAME answer comes back for every qtype, so collect then dedupe --
  # otherwise a single CNAME host prints once per type queried.
  for t in A AAAA CNAME MX TXT; do
    dig +noall +answer @"$NS" "$h.$DOMAIN" "$t"
  done | sort -u
done

echo
echo ";; --- mail policy / DKIM ---"
for h in "${TXT_HOSTS[@]}"; do
  dig +noall +answer @"$NS" "$h.$DOMAIN" TXT
  dig +noall +answer @"$NS" "$h.$DOMAIN" CNAME
done

echo
echo ";; --- wildcard probe (empty = no wildcard) ---"
dig +noall +answer @"$NS" "zzq7x-nonexistent-probe.$DOMAIN" A

echo
echo ";; --- concatenated TXT values (paste-ready) ---"
for h in "$DOMAIN" "${TXT_HOSTS[@]/%/.$DOMAIN}"; do
  dig +short @"$NS" "$h" TXT 2>/dev/null | while IFS= read -r line; do
    [ -z "$line" ] && continue
    # Join adjacent quoted strings with no separator, per RFC 7208 / DKIM rules.
    printf '%s\t%s\n' "$h" "$(printf '%s' "$line" | sed 's/" "//g; s/^"//; s/"$//')"
  done
done
